services:
  db:
    image: postgres:15
    volumes:
      - ./db:/var/lib/postgresql/data/
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: "always"
    command: sh -c "python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - staticfiles:/usr/src/app/staticfiles
    expose:
      - "${DJANGO_PORT}"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  nextapp:
    image: nextjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deploy
    restart: "always"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
    restart: "always"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - staticfiles:/usr/src/app/staticfiles
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/logs/:/var/logs:rw

    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - 443:443
    depends_on:
      - backend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  staticfiles:
