services:
  nextapp:
    image: blogfrontend:prod
    restart: "always"

  nginx:
    image: blognginx:prod
    restart: "always"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - staticfiles:/usr/src/app/staticfiles
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/logs/:/var/logs:rw

    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${SSL_PORT}:${SSL_PORT}
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  staticfiles:
